### ISSUE TITLE
ember-container-query needs to depend on ember-auto-import in order to use ember-modifier

### ISSUE THREAD

**Issue by st-h** [ijlee2/ember-container-query#176]
## Describe the bug 🐞

I just upgraded all dependencies in my app and now I am seeing the error:
`ember-container-query needs to depend on ember-auto-import in order to use ember-modifier`. I had a look at `package.json` but could not spot any ember-auto-import dependency. I think this is a requirement since ember-modifier v4.0: https://github.com/ember-modifier/ember-modifier/issues/602

## Expected behavior 🤔

Build does not error.

## Minimal reproduction 🔬

Describe steps to reproduce the behavior:

Create an app with ember-modifier >= 4.0 and install ember-container-query

**Comment by ijlee2** [comment]
Hi, @st-h. Since [`v4.0.0-alpha.1`](https://github.com/ijlee2/ember-container-query/releases/tag/4.0.0-alpha.1), `ember-container-query` has been a [v2 addon](https://github.com/embroider-build/embroider/blob/main/ADDON-AUTHOR-GUIDE.md).

What this means for the end-users of this addon is, their project must have `ember-auto-import@v2` installed. (A v1 addon that depends on `ember-modifier@v4` _does_ need to declare `ember-auto-import@v2` as one of its dependencies.)

To confirm, does your project currently have `ember-auto-import@v2`? You mentioned that you updated all dependencies in your app, so I wasn't sure.

At any rate, I think the confusion over which project is responsible for installing `ember-auto-import@v2` could have been prevented, had I updated [the Compatibility section under `README`](https://github.com/ijlee2/ember-container-query/tree/4.0.0-alpha.6#compatibility) before releasing `v4.0.0-alpha.1`.

Would you like to open a pull request to do so? You can update the section to look something like [the one for `embroider-css-modules`](https://github.com/ijlee2/embroider-css-modules/blob/0.1.0/embroider-css-modules/README.md#compatibility). (If you don't have time, I can work on it later today.)

**Comment by st-h** [comment]
Well, now I am not sure if I even understand that issue correctly. I have auto-import 2.6. in my app. I tried to upgrade to ember-container-query v4.0.0-alpha.6, but I am still seeing the same error. When looking at the source, I do not see an entry for ember-auto-import within ember-container-query `package.json`. As far as I understood it, an add-on needs to have a `ember-auto-import` v2 dependency in order to use `ember-modifier` v4. When I downgrade `ember-modifier` to v3, everything works again. Afaik, in order to resolve this issue, ember-container-query needs to define a dependency on `ember-auto-import` > 2.0.

**Comment by ijlee2** [comment]
Thanks for confirming the version of `ember-auto-import`. It is a strange case and I'll have to look into what's happening by creating an app and testing possible cases.

If you look at the lock file, do you perhaps see multiple versions of `ember-auto-import` or of `ember-modifier`? Are you perhaps using resolutions to enforce one version?

**Comment by st-h** [comment]
Oh, I see after reading through the related issue. This might be more complicated than expected. I've seen similar issues with other addons where adding auto-import as a dependency did resolve the issue. But I am not so up-to-date with the new addons things.

**Comment by ijlee2** [comment]
I ran `ember new hello-world` to create an Ember app with `npm` as the package manager. (`docs-app` already uses `yarn` so I wanted to test `npm` instead.)

Initially, `package.json` looked like,

```json
{
  "name": "hello-world",
  "devDependencies": {
    "ember-auto-import": "^2.6.3",
    "ember-cli": "~4.12.1",
    "ember-modifier": "^4.1.0",
    "ember-source": "~4.12.0",
  },
  "engines": {
    "node": "14.* || 16.* || >= 18"
  },
  "ember": {
    "edition": "octane"
  }
}
```

Afterwards, I ran `ember i ember-container-query`, which installed `v4.0.0-alpha.6`. I was able to start the app with `ember s` without encountering an error.

I also didn't see an error when I:

- Set the version of `ember-modifier` to `3.2.7` and ran `npm install`
- Used `npm`'s `overrides` key (similar to `yarn`'s `resolutions` key) to install one version of `ember-modifier` (still `3.2.7`)

I did see an error when I:

- Set the version of `ember-auto-import` to `1.12.1` (I had to downgrade `ember-source` and a few other packages)

    ```sh
    To use these addons, your app needs ember-auto-import >= 2: @ember-data/adapter, @ember-data/debug, @ember-data/model, @ember-data/record-data, @ember-data/serializer, @ember-data/store, ember-data, ember-qunit, ember-source

    # After downgrading the packages above
    hello-world has ember-auto-import 1.12.1 which is not new enough to use ember-container-query. It needs to upgrade to >=2.0
    ```

I wonder if you may have another addon that depends on `ember-modifier`. I don't know of a v1 addon that depends on `ember-modifier@v4` but forgot to list `ember-auto-import@v2` as its dependency. If there is such a v1 addon, I could try installing that in `hello-world` and see if I get an error.

**Comment by st-h** [comment]
I've been able to finally resolve this by cleaning up the auto-import dependencies in my project. Having auto-import v1 and v2 in a  project seemed to cause the issue. Many thanks for the support.

**Comment by ijlee2** [comment]
@st-h Thank you for the update. Glad to hear that you resolved the issue.
