### ISSUE TITLE
Dynamic Root Elements

### ISSUE THREAD

**Issue by chadian** [ijlee2/ember-container-query#38]
## I would like to see... 🙋‍♀️🙋‍♂️
Based on our discussion @ijlee2, it might be a useful feature to see the possibility of customizing the root element of the container.

## Why and how 💬
How: It looks like this is possible now and is considered stable based on `ember-element-helper`. The [compatibility](https://github.com/tildeio/ember-element-helper#limitations) might be limited to Ember 3.11 and up if the modifier needs to be attached to the element. 

Why: Keeping markup semantic and for cases where the markup element is important (possibly for css selectors)

**Comment by ijlee2** [comment]
Thanks for writing up the issue, @chadian. I agree that it's important to allow a dynamic tag instead of `<div>` to facilitate accessibility and semantic HTML.

Because I limited the addon support to Ember 3.16+ (and conjectured that the addon may work for 3.12-3.15), we should be okay with using `ember-element-helper` to solve the problem.


### Potential problem

Today, I read the [README](https://github.com/tildeio/ember-element-helper) and [RFC #389](https://github.com/emberjs/rfcs/blob/master/text/0389-dynamic-tag-names.md) to understand the ramifications of allowing a dynamic tag. The RFC has a section called [How we teach this](https://github.com/emberjs/rfcs/blob/master/text/0389-dynamic-tag-names.md#how-we-teach-this). It suggests that a developer should follow the WAI-ARIA specification (e.g. assign the right role) when changing the tag.

I'm okay with allowing [`...attributes`](https://github.com/ijlee2/ember-container-query/blob/1.0.2/addon/components/container-query.hbs#L6) to be used to help a developer follow the WAI-ARIA spec, in addition to its original, sole purpose of helping the developer pass `class` or `local-class`.

I think, in this addon's README, we will need to add a warning that changing the tag and passing more things (possibly in the right order) to `...attributes` should be done with care.


### Action items

If you'd like, let's start working on this next week (whenever you are free).

As I don't have much experience with accessibility, I think it'd be good to reach out to the Ember A11y team on Discord (at `#topic-a11y` channel). I'd like to know:

- Can a developer use any tag, or are there tags that we should disallow, in the context of container queries (an element resize)?
- Is using `...attributes` to allow a developer to pass things to meet WAI-ARIA spec the right Ember Octane way? Or is there an alternative approach that better separates the boundary between the `<ContainerQuery>` component and the consuming component?

Please let me know what you think and questions that you may have. Thanks again for your help!

**Comment by ijlee2** [comment]
Reference(s), mainly for myself so that I don't slack ☺️

- June 18. Asked questions listed in `Action items` on [`#topic-a11y` channel](https://discordapp.com/channels/480462759797063690/480523441082990612/723172804723212379).

**Comment by chadian** [comment]
Thanks for taking the lead on figuring out the accessibility piece to having dynamic root elements. I don't currently have the time to jump in on implementation for at least 3 more weeks but will be watching this issue and will contribute where I can. I am very much looking forward to seeing this land though so I will circle back.

**Comment by ijlee2** [comment]
@chadian I think I can work on trying out `ember-element-helper` next week. Trying to take things easy and not code too much during the covid outbreak. (Trying but failing 🙂)

After merging the PR for this issue, we'll probably want to look at how we can bring a solution back to `ember-fill-up`.
