### ISSUE TITLE
Removal of default css styles?

### ISSUE THREAD

**Issue by st-h** [ijlee2/ember-container-query#82]
## I would like to see... 🙋‍♀️🙋‍♂️

Removal of default css.

## Why and how 💬

I noticed that the included default styles was causing issues when using this addon with my app. I tried to override the applied styles, but at least with safari (chrome was ok) this lead to different behaviour, than when the styles wouldn't be present at all. In order to solve this, I started to use a fork of this addon, which did not contain the css styles. I never had to accommodate for the removal of those styles. Do you think it would be possible to remove the styles at all?

**Comment by ijlee2** [comment]
Thanks for the suggestion. Since Node 10 support will be dropped soon, I think it is possible to make a major release, where we may also replace the resize modifier and remove the default stylesheet.

To clarify, I had added `width: 100%;` and `height: 100%` because I had thought this would allow the container to receive the correct available width and height from its parent element. I can imagine that this might not be what a developer always wants, and agree that it's easier to ask the developer to explicitly set `width` and `height`, rather than to ask them to assume `100%`.

Let me check what would happen if default stylesheet isn't present in the demo app and possibly a couple of other apps.

**Comment by ijlee2** [comment]
I took screenshots of what the demo app looks like with and without the default styles.

The album and dashboard pages don't turn out to be the same. The form page does, but likely because there isn't any other component rendered besides `<Form>`.

## A. Album

### With default styles

<img width="1440" alt="" src="https://user-images.githubusercontent.com/16869656/145715769-36378aa1-2525-4195-87a9-795e3c05cc63.png">

### Without default styles:

<img width="1440" alt="" src="https://user-images.githubusercontent.com/16869656/145715776-c3e38e39-1718-4f16-9433-4476724d14dd.png">


## B. Dashboard

### With default styles

<img width="1440" alt="" src="https://user-images.githubusercontent.com/16869656/145715778-737b27a7-1c88-47b9-8bac-d54e2f7082e0.png">

### Without default styles

<img width="1440" alt="" src="https://user-images.githubusercontent.com/16869656/145715784-369c7e65-3074-47c1-b0c4-627445c9d296.png">


## C. Form

### With default styles

<img width="1440" alt="" src="https://user-images.githubusercontent.com/16869656/145715791-24814f23-fcfb-497a-acc0-4e036266772a.png">

### Without default styles

<img width="1440" alt="" src="https://user-images.githubusercontent.com/16869656/145715795-c18e785a-c0b5-45fd-b63f-a0845f7bc894.png">

**Comment by ijlee2** [comment]
@st-h Can you provide me a demo app or a sample code, which replicates the issue that you had encountered with Safari? If I understood you right, I think you might have tried overriding the default styles by writing,

```css
.reset-default-styles {
  height: auto;
  width: auto;
}
```

```handlebars
<ContainerQuery class="reset-default-styles">
  ...
</ContainerQuery>
```

Is my assumption above correct?

**Comment by st-h** [comment]
@ijlee2 Yes, I am pretty sure that was what I was doing. It worked fine in Chrome and Firefox, but Safari was showing a different behaviour when setting it back to default values - quite weird behaviour. The only fix I could find, was to remove those styles, so I won't have to override them. It's been quite a while now since I added ember-container-query, so I don't have a demo app or sample code. The app I am working on is quite complex and at the moment not open source. I can give the current alpha version a try and see into what issues I'll run into, though.

**Comment by st-h** [comment]
Regarding the screen shots. Yes, where those styles are needed, they would need to be applied manually. My issue was that the default styles did not fit my use case, and I could not reset them by overriding because safari would show a different behaviour. This really sounds like a bug with Safari... but well.. what can we do about that? Those versions are already out there...

**Comment by st-h** [comment]
@ijlee2 sorry about the late reply. lots of work at the moment. I tried out the 2.0.0-alpha.0 and here is a screenshoot of the issues I am still observing with safari:

Here is the 2.0.0-alpha.0. I am overriding the container query styles as you recommended. However, this leads to a height that exceeds the parent container.
![Screenshot 2021-12-23 at 12 36 53](https://user-images.githubusercontent.com/5768353/147236588-a2656320-6fb2-4ba9-902e-ec1d1b730202.png)

This is the exact same code, I only replaced container query with my fork that does not include the default styles. 
![Screenshot 2021-12-23 at 12 54 47](https://user-images.githubusercontent.com/5768353/147237072-a7f76e33-4bca-4652-af0d-f969af50d045.png)

This is my fork without the styles to override height and width (same result):
![Screenshot 2021-12-23 at 12 40 28](https://user-images.githubusercontent.com/5768353/147236581-582b8185-657a-4050-93ed-7857e89bcf14.png)

The only solution I could find to fix this, was to remove the default styles from container-query. I've also tried to use `unset` instead of `auto` for width and height, but the results are the same. 

The parent element has `display: flex` btw. In a case like this it does not make any sense at all to try to set the width and the height to 100%, because a smaller height than the parent container is intended. Therefore I still think it would be better to remove the default styles and manually add them where appropriate instead of assuming a specific situation and provide styles that only support that specific case.

**Comment by ijlee2** [comment]
@st-h No worries, thank you for providing screenshots. I'll try to find time on Sunday/Monday to look at the issue closely.

**Comment by st-h** [comment]
Hi @ijlee2. Did you possibly find some time to look into removing the default css styles? I am still using a fork of this addon, because I run into unfixable layout issues when the default styles are applied that are shipped with ember-container-query.

**Comment by ijlee2** [comment]
Hi, @st-h. I'm much sorry for a late response. I wanted to take time to figure out a change that is non-breaking and doesn't expand the API unnecessarily (e.g. allow passing a Boolean as an argument to disable the default styles).

In `v2.1.1`, the addon exports a modifier called `{{container-query}}`. I believe, with the modifier approach, we can handle the case of not applying the default styles.

Here's a sample code, where the modifier is applied to an HTML element:

```hbs
<div
  local-class="container"
  {{container-query
    features=(hash
      wide=(cq-width min=600)
    )
  }}
>
  Hello world!
</div>
```

```css
.container {
  border: 1px solid orange;
}

.container[data-container-query-wide] {
  border: 1px solid steelblue;
}
```

One could also create a component to enable reusing code. What do you think?

**Comment by ijlee2** [comment]
To recap: Starting `v2.1.1`, end-developers can use the `{{container-query}}` modifier, to opt out of the `<ContainerQuery>` component. I'll mark the issue as fixed.

**Comment by st-h** [comment]
Thank you. Actually, I am currently working on a redesign. Surprisingly I could override all the styles when necessary without any issues. Today I finally checked if this might be related to a fix in Safari, however it turned out that the issue still exists. Seems to be a pretty weird edge case. Yet, I think the option to use a modifier when needed will work fine. I am glad I no longer need to maintain a fork 😊
